### ISSUE TITLE
Wrong version of Node on Netlify

### ISSUE THREAD

**Issue by SilvanZwick** [Aluben-service/Aluben-sveltekit#47]
As you can see below, I have opened a pull request, and all the checks have failed because Netlify is running the wrong version of Node.
<img width="682" alt="image" src="https://github.com/user-attachments/assets/680e1b0c-47fd-4f0f-8785-1114ac083823">
![image](https://github.com/user-attachments/assets/cf79f726-dc0a-4403-8d47-9a2dccbfb815)

**Comment by asc2563** [comment]
yea I know. there's not alot I can do about that
